<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: eloquent.proto

namespace Esanj\RemoteEloquent\Grpc;

use Esanj\RemoteEloquent\Grpc\GPBMetadata\Eloquent;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>eloquent.query.QueryRequest</code>
 */
class QueryRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string sql = 1;</code>
     */
    protected $sql = '';
    /**
     * Generated from protobuf field <code>repeated string bindings = 2;</code>
     */
    private $bindings;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * @type string $sql
     * @type array<string>|\Google\Protobuf\Internal\RepeatedField $bindings
     * }
     */
    public function __construct($data = NULL)
    {
        Eloquent::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string sql = 1;</code>
     * @return string
     */
    public function getSql()
    {
        return $this->sql;
    }

    /**
     * Generated from protobuf field <code>string sql = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSql($var)
    {
        GPBUtil::checkString($var, True);
        $this->sql = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string bindings = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getBindings()
    {
        return $this->bindings;
    }

    /**
     * Generated from protobuf field <code>repeated string bindings = 2;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setBindings($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->bindings = $arr;

        return $this;
    }

}

