<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: eloquent.proto

namespace Esanj\RemoteEloquent\Grpc;

use Esanj\RemoteEloquent\Grpc\GPBMetadata\Eloquent;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>eloquent.query.QueryResponse</code>
 */
class QueryResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .eloquent.query.DataRow rows = 1;</code>
     */
    private $rows;
    /**
     * Generated from protobuf field <code>uint64 affected_rows = 2;</code>
     */
    protected $affected_rows = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * @type int|string $affected_rows
     * }
     */
    public function __construct($data = NULL)
    {
        Eloquent::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .eloquent.query.DataRow rows = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRows()
    {
        return $this->rows;
    }

    /**
     * Generated from protobuf field <code>repeated .eloquent.query.DataRow rows = 1;</code>
     * @return $this
     */
    public function setRows($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, DataRow::class);
        $this->rows = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 affected_rows = 2;</code>
     * @return int|string
     */
    public function getAffectedRows()
    {
        return $this->affected_rows;
    }

    /**
     * Generated from protobuf field <code>uint64 affected_rows = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAffectedRows($var)
    {
        GPBUtil::checkUint64($var);
        $this->affected_rows = $var;

        return $this;
    }

}

