<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: eloquent.proto

namespace Esanj\RemoteEloquent\Grpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>eloquent.query.QueryResponse</code>
 */
class QueryResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .eloquent.query.DataRow rows = 1;</code>
     */
    private $rows;
    /**
     * Generated from protobuf field <code>uint64 affected_rows = 2;</code>
     */
    protected $affected_rows = 0;
    /**
     * Auto-increment id produced by an INSERT. 0 means the statement produced none
     * (a non-insert, or a table with a client-generated key).
     *
     * Generated from protobuf field <code>uint64 last_insert_id = 3;</code>
     */
    protected $last_insert_id = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Esanj\RemoteEloquent\Grpc\DataRow>|\Google\Protobuf\Internal\RepeatedField $rows
     *     @type int|string $affected_rows
     *     @type int|string $last_insert_id
     *           Auto-increment id produced by an INSERT. 0 means the statement produced none
     *           (a non-insert, or a table with a client-generated key).
     * }
     */
    public function __construct($data = NULL) {
        \Esanj\RemoteEloquent\Grpc\GPBMetadata\Eloquent::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .eloquent.query.DataRow rows = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRows()
    {
        return $this->rows;
    }

    /**
     * Generated from protobuf field <code>repeated .eloquent.query.DataRow rows = 1;</code>
     * @param array<\Esanj\RemoteEloquent\Grpc\DataRow>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRows($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Esanj\RemoteEloquent\Grpc\DataRow::class);
        $this->rows = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 affected_rows = 2;</code>
     * @return int|string
     */
    public function getAffectedRows()
    {
        return $this->affected_rows;
    }

    /**
     * Generated from protobuf field <code>uint64 affected_rows = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAffectedRows($var)
    {
        GPBUtil::checkUint64($var);
        $this->affected_rows = $var;

        return $this;
    }

    /**
     * Auto-increment id produced by an INSERT. 0 means the statement produced none
     * (a non-insert, or a table with a client-generated key).
     *
     * Generated from protobuf field <code>uint64 last_insert_id = 3;</code>
     * @return int|string
     */
    public function getLastInsertId()
    {
        return $this->last_insert_id;
    }

    /**
     * Auto-increment id produced by an INSERT. 0 means the statement produced none
     * (a non-insert, or a table with a client-generated key).
     *
     * Generated from protobuf field <code>uint64 last_insert_id = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLastInsertId($var)
    {
        GPBUtil::checkUint64($var);
        $this->last_insert_id = $var;

        return $this;
    }

}

