syntax = "proto3";

package eloquent.query;


option php_namespace = "Esanj\\RemoteEloquent\\Grpc";
option php_metadata_namespace = "Esanj\\RemoteEloquent\\Grpc\\GPBMetadata";

service RemoteEloquentService {
  rpc RunQuery (QueryRequest) returns (QueryResponse);
}

message QueryRequest {
  string sql = 1;

  repeated string bindings = 2;
  repeated uint32 null_bindings = 3;
}

message DataRow {
  map<string, string> fields = 1;
  repeated string null_fields = 2;
}

message QueryResponse {
  repeated DataRow rows = 1;

  uint64 affected_rows = 2;

  uint64 last_insert_id = 3;
}
