<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: eloquent.proto

namespace Esanj\RemoteEloquent\Services\GRPC;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>eloquent.query.QueryResponse</code>
 */
class QueryResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .eloquent.query.DataRow rows = 1;</code>
     */
    private $rows;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Esanj\RemoteEloquent\Services\GRPC\DataRow>|\Google\Protobuf\Internal\RepeatedField $rows
     * }
     */
    public function __construct($data = NULL) {
        \Esanj\RemoteEloquent\Services\GRPC\GPBMetadata\Eloquent::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .eloquent.query.DataRow rows = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRows()
    {
        return $this->rows;
    }

    /**
     * Generated from protobuf field <code>repeated .eloquent.query.DataRow rows = 1;</code>
     * @param array<\Esanj\RemoteEloquent\Services\GRPC\DataRow>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRows($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Esanj\RemoteEloquent\Services\GRPC\DataRow::class);
        $this->rows = $arr;

        return $this;
    }

}

