<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: eloquent.proto

namespace Esanj\RemoteEloquent\Services\GRPC\GPBMetadata;

class Eloquent
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xA6\x03\x0A\x0Eeloquent.proto\x12\x0Eeloquent.query\"\x1B\x0A\x0CQueryRequest\x12\x0B\x0A\x03sql\x18\x01 \x01(\x09\"m\x0A\x07DataRow\x123\x0A\x06fields\x18\x01 \x03(\x0B2#.eloquent.query.DataRow.FieldsEntry\x1A-\x0A\x0BFieldsEntry\x12\x0B\x0A\x03key\x18\x01 \x01(\x09\x12\x0D\x0A\x05value\x18\x02 \x01(\x09:\x028\x01\"6\x0A\x0DQueryResponse\x12%\x0A\x04rows\x18\x01 \x03(\x0B2\x17.eloquent.query.DataRow2`\x0A\x15RemoteEloquentService\x12G\x0A\x08RunQuery\x12\x1C.eloquent.query.QueryRequest\x1A\x1D.eloquent.query.QueryResponseBV\xCA\x02\"Esanj\\RemoteEloquent\\Services\\GRPC\xE2\x02.Esanj\\RemoteEloquent\\Services\\GRPC\\GPBMetadatab\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

